### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by pepelsbey**
Currently all images are not optimized at all: they all just PNGs with alpha transparency. I guess it gives perfect quality and you don’t have to bother while exporting assets. But it takes 2 MB to load a simple page. Way too much.

So what it did:

1. Converted all images to JPG with decent compression (70-80%)
2. Created 1x and 2x versions used in `srcset` attributes to load 2x only when it’s needed
3. Fixed size in `manifest.json`: 600 instead of 512 (actual size of the picture)

What it gives:

1. 463 KB on 1x screen (4,3 times less)
2. 877 KB on 2x screen (2,2 times less)

…without any noticable regression.

I hope you’ll accept this PR and will be careful with your next project.

### CODE REVIEW

**Comment by andrewda** [comment]
Is the black outline around the white logos wanted?

**Comment by pepelsbey** [comment]
I may have chosen the wrong matte color for white logo. Let me check.

**Comment by pepelsbey** [comment]
Sorry for delay: yes, I specifically optimized white logo to use `#333333` color matte since it’s only used on such background and there’s no need in alpha transparency. I guess it’s good to go then :)

**Comment by housseindjirdeh** [comment]
Awesome, again - thanks a million for this :)

**Pull request merged**
